Added turn on lights for dark emails that have wrong css.
Criptext/Android-Email-Client pull request #690
Opened 2020-09-04 05:18 UTC by jorgeblacio

- Also fixed an issue with the default address and the email not been sent with the selected address.
- Also added a custom report when an upload fails so that we can check each case in a more detailed way.

2020-09-08 13:30 UTC, danieltigse requested changes

2020-09-08 13:30 UTC, danieltigse commented on src/main/kotlin/com/criptext/mail/scenes/composer/ComposerController.kt
> +//            if(model.selectedAddress.isEmpty()) model.selectedAddress = activeAccount.userEmail
Remove comments

2020-09-09 17:42 UTC, Hirobreak approved these changes

2020-09-11 00:42 UTC, danieltigse approved these changes

2020-09-11 00:42 UTC, merged